### ISSUE TITLE
Migrate existing Telegram plugin to new framework

### ISSUE THREAD

**Issue by ailisp** [near/neardevhub-widgets#175]
**Problem**
Currently, community admins do not have an intuitive way to enable and manage the Telegram plugin. When an admin updates the "Telegram handles" field in the About section, that adds the Telegram tab.

**User Story**
As a community admin, I want the ability to decide if to enable or disable the Telegram. I also want to clearly understand where to configure this page in a consistent way.

**Acceptance Criteria**
- Telegram plugin aligns with the new framework (#253). So an admin can enable, configure, or remove the plugin in the community settings page.
- If a community admin enables the Telegram plugin, the Telegram tab shows up on the community page navigation. And the page itself is populated with the Telegram content set in the Telegram plugin section. Not from the About section.
- If an admin enables the Telegram plugin, they can click configure to customize the the tab name as well as the Telegram specific fields, including:
  - Telegram channels. Ideally, admins can add multiple Telegram channels, each in a separate field box. And each field would have a prefix that says: "https://t.me/" to make it clear what part of the Telegram URL the user needs to enter.
- Community admin should have a way to preview GitHub board from the configure settings. 
- If an admin enables the Telegram plugin, the Telegram field(s) are required
- There is no disruption to old/existing Telegram plugins
- There is migration option provided for existing communities to transition to the new framework

**Comment by ori-near** [comment]
@carina-akaia Thanks for creating this ticket. I added very clear testable acceptance criteria to ensure we don't miss anything. Please let me know if you have any questions.

**Comment by petersalomonsen** [comment]
Tested this a bit for myself now, and also set it up in my preview environment ( no changes at this point ).

https://near.social/devgovgigs.petersalomonsen.near/widget/gigs-board.pages.community.activity?handle=special

I see that adding a Telegram handle adds a Telegram tab. I believe that we should ( rather than having github/telegram as default widgets - even with a toggle ) be able to add any widget, so rather have an "add widget" button like shown in the screenshot below.

And when clicking that button, a dropdown to select the widget you want to add. Finally when added you get a configuration section for that widget, and also the option to delete it.

<img width="737" alt="image" src="https://github.com/near/neardevhub-widgets/assets/9760441/1a03958c-4102-4789-9b05-55dc317a0d9b">

**Comment by ori-near** [comment]
Hi @petersalomonsen – yes, this is definitely the direction we want to move forward with. Well may have to think through the actual UX a bit more ... but the idea of enabling toggling on/off additional widgets and then customizing them in the settings would be great. Thank you.

**Comment by petersalomonsen** [comment]
Some more screenshots on the add widget experience:

<img width="896" alt="image" src="https://github.com/near/neardevhub-widgets/assets/9760441/75ba9a52-202e-46d8-84ba-ba21d4486da1">

and after adding the "music tracker" widget. 

<img width="912" alt="image" src="https://github.com/near/neardevhub-widgets/assets/9760441/c3a621f8-2ebc-40bb-8389-469fa4ba82be">

**Comment by carina-akaia** [comment]
@petersalomonsen I'd rename "Add widget" to "Add page" in order to make it more explanatory

**Comment by ori-near** [comment]
A user should also have the ability to customize the widget's tab name. And also to delete the widget.

**Comment by elliotBraem** [comment]
Included in this scope should be creating a "CommunityAddon"; an instance in the devhub contract:

pub struct CommunityAddOn {
    id: String,
    title: String,
    description: String,
    src: String,
    schema: String,
    custom_configurator: String
    icon: String
}
Telegram has it's own schema that is currently hardcoded in gigs-board.pages.community.configurator. After this is added, most of the scope should be completed because of the framework. This migration looks minimally invasive.

> Community admin should have a way to preview GitHub board from the configure settings.

Oops! *Telegram board.

I think this is a solid M effort, with that potentially being a safe overestimate. @ori-near
