### ISSUE TITLE
[Landing Page UX] Ability to filter submitted ideas by author

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#18]
**Challenge**
Currently, it is challenging for a user to easily find posts that they or specific people posted. This can lead to frustrating interactions and potentially missed engagement.

**Opportunity**
Users need the ability to easily find ideas by a specific user.

**Solution**
Filter posts: Allow users to filter their posts by authors (in addition to labels)

**Comment by frol** [comment]
I believe notifications are implemented, but filtering also makes sense to me.

**Comment by ailisp** [comment]
Yes notifications of interactions on their posts are available in near.social's notification panel. 

@ori-near For filter posts, could you confirm: does it mean filter posts by any given account id?

Assume there're `frol.near`, `ori.near` and my account is `bo.near`. Filter posts mean I can view all `frol.near` `ori.near`'s posts. My posts mean I can view all my posts. Filtering pages looks same as the list of post page with an selected label. But the difference is this is filter by author instead of label. 

Does my understanding match your proposed idea? Do you have additional details?

**Comment by ailisp** [comment]
As discussed with @ori-near ,  We'll prioritize "Filter posts" in this ticket

**Comment by ori-near** [comment]
Thank you @ailisp! Currently the "search by tag" search box operates as a filter by label dropdown. I propose that we introduce two filters (by author username) and labels. Something similar to GitHub's functionality:

Filter by Author:
![Screen Shot 2023-03-07 at 6 04 25 PM](https://user-images.githubusercontent.com/110252255/223600514-ef79aaaa-40d9-41f3-88be-56f07ad8a77a.png)

Filter by Username:
![Screen Shot 2023-03-07 at 6 03 36 PM](https://user-images.githubusercontent.com/110252255/223600388-d0786074-f30d-4798-9c8b-361a0f887a47.png)

**Comment by frol** [comment]
FYI, there is a hackathon submission with search improvements and some other features: https://near.social/#/devgovgigs.near/widget/gigs-board.pages.Post?id=288

@ori-near @ailisp @nearmax Let's try it out and see if there is anything we want to merge from there and reach out to the authors to invite them to submit a PR.

**Comment by ailisp** [comment]
This team proposed five widgets are all very useful! I'd like to discuss their submission. The search implemented by the team is a full text search, which is more impressive than filter by author, but it doesn't directly relevant to this issue. Therefore we'll make a separate PR for this ticket.

**Comment by ailisp** [comment]
Hi @nearmax , please deploy contract to production using steps here: https://github.com/near/devgigsboard/pull/14#issuecomment-1498426042

**Comment by ori-near** [comment]
Hi @ailisp – I believe Max completed the steps you requested. If you are still blocked, please move this ticket to the "Blocked" column and tag the appropriate person with more details. Otherwise, we assume this ticket is not blocked.

**Comment by ailisp** [comment]
Yeah it's not blocked. Update estimation to 1 day for enabling this on UI

**Comment by ori-near** [comment]
Hi @ailisp thanks for shipping this. Super helpful. I'm brainstorming a few minor tweaks for us to iterate on this:

- Show "Author 🔽" instead of a search box similar to GitHub to avoid so many search fields. Same thing for tags.
- Show username picture in the drop down (if won't degrade performance)
- Show user's first and last name too if available 
- Show your own username as the first one on the list

I will create separate tickets for this.

**Comment by ailisp** [comment]
Hi @ori-near ! This would be challenging but I can try. The reason is we currently use TypeAhead as a near-social provided API, which is a black box component rendered outside the near-social vm. It is unable to customize it unless p aste it's source code to have it running inside vm, but we often hit limitations doing such. 

If we can do that, will do; If there are limitations, currently tools team are working on a near social viewer 2.0 to allow any react component
