### ISSUE TITLE
When a user submits a reply to an existing post, the editor preserves the content

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#199]
**Describe the bug**
Since the state preservation was introduced in https://github.com/near/neardevhub-widgets/issues/87, there's a new problem during the post reply experience where the editor preserves the content in the reply even after the user clicks submit. This makes it super confusing for users – because it appears that they stay in edit mode, and they may end up posting multiple times. Also, there's no way for them to clear the content from the editor.

**To Reproduce**
1. Go to this post https://near.social/#/devgovgigs.near/widget/gigs-board.pages.Post?id=849 (make sure to open it as a new tab, not within the feed)
2. Click reply sponsorship
3. Fill out per the attached screenshot
4. Click Submit
5. Click confirm 
6. The sponsorship is posted (see green area), but it still shows the editor and preview above it (red).

![Screenshot 2023-07-11 at 5 26 45 PM](https://github.com/near/neardevhub-widgets/assets/110252255/bad25159-37cd-4fca-9c58-b40bb2ec0d15)

**Expected behavior**
Expectation 1: Preserved state should be cleared once the content is post successfully:
When a user clicks submit, the content is posted, and the editor mode disappears.

Expectation 2: As a user, I want to be able to abort the editing process so that when I reload the page I don't have to be forced indefinitely into my edited draft.
When a user clicks cancel, the editing mode disappears. 

**Screenshots**
![Screenshot 2023-07-11 at 8 55 23 AM](https://github.com/near/neardevhub-widgets/assets/110252255/ac7800df-187e-426c-9ddb-a49110f44f86)

**Comment by ori-near** [comment]
@near-akaia-root Please feel free to use this test post to test this:
https://near.social/#/devgovgigs.near/widget/gigs-board.pages.Post?id=0

**Comment by near-akaia-root** [comment]
@ori-near which wallet do you use for tx signing?

**Comment by petersalomonsen** [comment]
@ori-near @near-akaia-root 

This seems to be an issue on near.social, but not near.org.

Here the bug is present: https://near.social/#/devgovgigs.petersalomonsen.near/widget/gigs-board.pages.Feed
But here it's not: https://near.org/devgovgigs.petersalomonsen.near/widget/gigs-board.pages.Feed

The reason for this is that this feature depends on seeing `transactionHashes` in the query string after a post is submitted. This seem only to happen at near.org, while with near.social it does not.

@frol @ailisp

**Comment by near-akaia-root** [comment]
@petersalomonsen I think it also depends on the wallet used for transaction signing

**Comment by petersalomonsen** [comment]
@near-akaia-root if the wallet does not provide `transactionHashes` in the callback, yes then it will not delete the draft.

to delete the draft, you can simply provide `transactionHashes=blabla` in the query string. For example:

https://near.org/devgovgigs.petersalomonsen.near/widget/gigs-board.pages.Feed?transactionHashes=blabla

but if you try the same for near.social, it does not work:

https://near.social/?transactionHashes=blabla#/devgovgigs.petersalomonsen.near/widget/gigs-board.pages.Feed

So probably I think this needs to be fixed with near.social, to make sure that the `transactionHashes` is passed to the widget, and the problem might be that near.social is a bit older, and not up to date maybe?

**Comment by petersalomonsen** [comment]
I've created an issue in near.social for this: https://github.com/NearSocial/viewer/issues/175

**Comment by petersalomonsen** [comment]
This issue will be fixed by https://github.com/NearSocial/viewer/pull/176
