### ISSUE TITLE
Sponsorship reply form confuses users with "Sponsor" and duplicate information in preview

### ISSUE THREAD

**Issue by frol** [near/neardevhub-widgets#210]
**Describe the bug**

Replying with sponsorship produces unnecessary "Sponsored amount" and "Sponsor" in addition to the correct "Maximum amount" and "Supervisor" fields in **the preview**:

<img width="906" alt="image" src="https://github.com/near/neardevhub-widgets/assets/304265/bed0a305-cee7-4b5e-b5b7-0d389388d179">

Note: this is only an issue with the preview.

**To Reproduce**

1. Go to any post (https://near.social/#/devgovgigs.near/widget/gigs-board.pages.Post?id=842)
2. Click on "Reply" -> "Sponsorship"
3. Select "Yes" in "Are you funding their solution?"
4. Fill out the "Sponsored amount" and "Sponsor" (by the way, "Sponsor" is invalid in this context, it should be "Supervisor")

**Expected behavior**

1. The preview should only have "Maximum amount" and "Supervisor"  fields
2. "Sponsor" should be renamed to "Supervisor" in the Sponsorship reply form

**Comment by ori-near** [comment]
Thanks for filing this @frol. I surfaced a similar concern to @Tguntenaar, as I believe this bug was introduced with https://github.com/near/neardevhub-widgets/issues/142. 

This bug introduced this same fields from the solution post in the sponsorship post:
![Screenshot 2023-07-27 at 2 29 28 PM](https://github.com/near/neardevhub-widgets/assets/110252255/92bcf16f-0cff-4b8d-9f2c-2cbb691f8f1d)

Please restore the original fields that the sponsorship pos had: Maximum Amount and Supervisor, remove the "Are you funding their solution" section, and make sure the preview renders correctly.
