### ISSUE TITLE
[Communities] Homepage stuck in loading state and won't display sidebar

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#235]
**Describe the bug**
I just created a new [Developer DAO community](https://near.social/devgovgigs.near/widget/gigs-board.pages.community.activity?handle=devdao). However, the homepage is stuck in a loading state and won't display the sidebar. I assume this is maybe because there are many posts on DevHub with the community tag `developer-dao`?

**To Reproduce**
1. Go to https://near.social/devgovgigs.near/widget/gigs-board.pages.community.activity?handle=devdao
2. See two errors: 
- Loading icon under the user profile of the first post
- Sidebar shows "Loading..." text 

**Expected behavior**
The page should load quickly and display all the author photos + the sidebar content/

**Screenshots**
![Screenshot 2023-08-09 at 4 58 40 PM](https://github.com/near/neardevhub-widgets/assets/110252255/59147d12-2b63-48bc-aea6-1905aa9ec96e)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browsers: Chrome, Safari
 - Version: Latest versions

**Comment by ori-near** [comment]
BTW for context, I created this community using the neardevgov.near account.

**Comment by elliotBraem** [comment]
Looked into this. 

First, the avatar for the user profile failing to load is not related to DevHub. This happens when a user uploads an invalid profile picture to their account. I've experienced this before with someone uploading an image that was too large -- there is not much validation in the profile editor. See Eunice's account on [near.social](https://near.social/mob.near/widget/ProfilePage?accountId=nearlove.near) and on [near.org](https://near.org/near/widget/ProfilePage?accountId=nearlove.near). Notice how it fails to load in either.

Regarding the sidebar, the issue lies in this code block here: 

<img width="568" alt="Screenshot 2023-08-10 at 2 22 19 PM" src="https://github.com/near/neardevhub-widgets/assets/16282460/a470cae4-17fa-4722-b691-e7045cdfad39">

Either root members or the community is null. After running it locally, I see that root members returns an object, but community is null. Why might community be null?

**Comment by ori-near** [comment]
Additional finding: It looks like the failed sidebar bug occurs when I enter `devdao` into the community handle in the edit community about section. But I just tried to change the handle to a different handle of `developer-dao` and that fixed the bug. Then I brought it back to devdao and the bug returned.
