### ISSUE TITLE
"Post" button on the Community pages does not work

### ISSUE THREAD

**Issue by frol** [near/neardevhub-widgets#320]
**Describe the bug**

<img width="1334" alt="image" src="https://github.com/near/neardevhub-widgets/assets/304265/6e54d658-f7d5-441d-a417-c788a3f682c8">

Clicking on that "Post" button does nothing.

**To Reproduce**
1. Go to https://near.social/devgovgigs.near/widget/gigs-board.pages.community.activity?handle=near-campus&nearDevGovGigsContractAccountId=devgovgigs.near
2. Click on 'Post'
3. Does not open any dialog or posting page

**Expected behavior**

New post form should open.

**Comment by elliotBraem** [comment]
There is a fix for this that was trying to get merged this morning -- I jsut saw that it failed to deploy because of :

#308 

```
"Error: 
   0: Error: Signer account <devgovgigs.near> doesn't have enough balance (0.106493814494444894185993 NEAR) after transaction.
"
```

devgovgigs.near must not have any more storage on social.near

![telegram-cloud-photo-size-1-5012579318559255290-y](https://github.com/near/neardevhub-widgets/assets/16282460/6d80dd3f-0a41-4ce2-bec2-9b2feec9bee3)
