### ISSUE TITLE
Display all posts including replies

### ISSUE THREAD

**Issue by nearmax** [near/neardevhub-widgets#324]
**Is your feature request related to a problem? Please describe.**
It is hard to see of activity happening on DevHub now that there is no option to see all replies.

**Describe the solution you'd like**
A button that shows all replies.

**Describe alternatives you've considered**
I couldn't come up with a better alternative.

**Comment by carina-akaia** [comment]
@ori-near I would like to tackle this task

**Comment by ori-near** [comment]
Hi @nearmax – thanks for sharing this. We actually had a planned solution for this as part of https://github.com/near/neardevhub-widgets/issues/114 through a sort button, see design:
![search](https://github.com/near/neardevhub-widgets/assets/110252255/ab939841-29ee-49a7-b217-da23882f7344)

I propose that as part of this ticket we implement the originally proposed scope below, which I believe addresses your concern. Please confirm if otherwise.

# Scope

**Problem**
Currently, users can only see parent level posts ordered by recency. However, users may want to see additional posts such as all replies so that they can get a sense for everything that's happening on DevHub. 

**User Story**
As a user, I want to have a sort filter experience so that I can easily find all posts.

**Acceptance Criteria**
- A user sees the updated search/filter UI elements (Search box, Sort dropdown, Author dropdown, and Label dropdown) per the design
- The sort label will have a dropdown with three options:
  - Latest – This is the default selection. It loads the most recent top-level posts and replaces the existing home button
  - Hottest – This shows the most popular posts and replaces the old hottest button
  - All replies – This shows all the replies (both parent or child level) in most recent order and replaces the existing recent button

----

Hey @carina-akaia – thanks for expressing interest here! Since @ailisp is focusing right now on all search improvements, I'd like to propose that he takes this on and can delegate to you if needed.
