### ISSUE TITLE
Activity feed does not display the most recent posts

### ISSUE THREAD

**Issue by frol** [near/neardevhub-widgets#465]
**Describe the bug**

I don't see the most recent posts on the feed:

https://near.social/devhub.near/widget/app?page=post&id=2099
https://near.social/devhub.near/widget/app?page=post&id=2100
https://near.social/devhub.near/widget/app?page=post&id=2101
https://near.social/devhub.near/widget/app?page=post&id=2102

**To Reproduce**

1. Go to https://near.social/devhub.near/widget/app?page=feed
2. There is no posts mentioned above

**Expected behavior**

I expect to see the top-level posts in the activity feed.

**Comment by elliotBraem** [comment]
I see this stop reflected in [near-query-api devhub_v32 query](https://near.org/dataplatform.near/widget/QueryApi.App?selectedIndexerPath=bo.near/devhub_v32&view=editor-window) (which is what we are using); the last post recorded is 2097 and then it just stops.

If I inspect [devhub_v34](https://near.org/dataplatform.near/widget/QueryApi.App?selectedIndexerPath=bo.near/devhub_v34&view=editor-window), then I can see the latest posts.

Checking diff between the two, this is all I see:

![Screenshot 2023-11-14 at 10 17 09 AM](https://github.com/near/neardevhub-widgets/assets/16282460/9e41752a-c560-4b6b-ba00-c6819a3c59ea)

I don't know why changes to Likes should effect these posts not showing up. I wonder if creating newer indexers (v32 -> v34) stops older indexers, or they expire in some way.

@ailisp any insight into what you're working on?

Although I don't think it would break anything, I'm hesitant to just go ahead and update to newest indexer without knowing more. I think I'd first like to migrate bo's indexer into this repository (as near-discover-components team does [here](https://github.com/near/near-discovery-components/tree/develop/indexers)) so that we can keep a devhub stable version, as well as enable others to collaborate and fix issues when they come up. 

Will ping others for comment

**Comment by ailisp** [comment]
The problem seems to be devhub_v32 stopped catching up new blocks after 105660205, but it's still showing as RUNNING and no error logs on queryapi dashboard. Before that it has been catching blocks for more than 20 hours. We need to figure out why it stopped catching up new blocks from query api backend logs.

**Comment by ailisp** [comment]
v34 has just stopped picking up new blocks since 105715517, but v35 still works. We need to figure out the reason and fix it otherwise the new indexer can still stop picking up new blocks in future.

**Comment by ailisp** [comment]
We found the issue https://github.com/near/queryapi/issues/407, the older indexers stop pick up new blocks, but with the newest indexer it works fine. So before this issue addressed, we should always use the latest indexer for picking up latest posts. Also, this means to we cannot create temp indexer for testing or implementing new features under the same account.
