### ISSUE TITLE
View post version history with differences

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#64]
**Problem**
The Gigs board currently does not display the editing history of posts, even though the information is stored in a smart contract. This makes it difficult for users to understand how the post has evolved over time, track the changes, and verify the accuracy.

**User Story**
As a Gigs board user, I want to view the history of a post and see the differences between each version so that I can better understand how the post changed over time.

**Acceptance Criteria**
- The version history is accessible from each post
- The version history displays a timestamp of each version and the the corresponding user account 
- The version history shows the differences between each version, highlighting any additions or deletions
- The version history is user friendly & intuitive
- Optional: The version history allows the user to compare any two versions

**Note**
- This idea was featured as a bounty at the [ETH Denver Hackathon](https://www.ethdenver.com). See proposed https://github.com/near/devgigsboard-widgets/pull/62.

**Comment by ori-near** [comment]
@ailisp Can you please add a size estimate to this?

**Comment by ailisp** [comment]
Trying: 
https://near.social/#/markeljan.near/widget/PostWithHistory?id=268&timestamp=1682382435187494750&compareTimestamp=1677857800212765894&referral=

looks like everything except 
> Optional: The version history allows the user to compare any two versions

has been implemented. So I estimates this to be 1 day of work.

**Comment by petersalomonsen** [comment]
To me the link above shows the diff between two versions as specified in the timestamps of the query strings, and it just works every now and then. I miss a list of the available versions, and I guess this would have to be a dropdown with multi-select to choose the versions to compare.

Need to study why this fails most of the time, and also find out how to get the list of the post versions, so if it turns out to be straight forward then I guess 1 day is within reach, but could also be more if some parts need to be reimplemented.

**Comment by petersalomonsen** [comment]
Ready for review https://github.com/near/neardevhub-widgets/pull/193

Based on the original work from https://near.social/#/markeljan.near/widget/PostWithHistory?id=268&timestamp=1682382435187494750&compareTimestamp=1677857800212765894&referral=
