### ISSUE TITLE
[Communities] Sync Telegram Activity

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#78]
**Problem**
Many of the Community Groups use Telegram and other social channels for discussions. However, our platform does not show real-time updates from those channels. This makes it hard for users to discover and keep track of conversations across the communities they care about. It also makes it hard for various roles/groups (e.g. Work Group members, DevDAO, etc) to coordinate monitoring effort of all channels, collect and aggregate feedback, and funnel it into the appropriate pipeline.

**Solution**
Implement a Telegram sync feature that enables each community page to show the latest activity from its corresponding Telegram channel. This will improve discoverability and engagement for the community, ultimately resulting in more contributions to the ecosystem.

**Acceptance Criteria**

- Integration with Telegram API to retrieve the latest activity from each channel
- Add admin capability for a user with admin permissions for a community to enable a "Telegram" tab and specify the various Telegram URLs
- If a community has Telegram enabled, display a new optional "Telegram" tab" along with the latest activity in real time
- If there are multiple telegram channels, separate them with a title and divider
- For MVP, please also populate these existing groups with the following Telegram channels:
  - Zero Knowledge: https://t.me/NearZeroKnowledge
  - Protocol: https://t.me/NEAR_Protocol_Community_Group
  - Tooling: https://t.me/NEAR_Tools_Community_Group
  - Contract Standards: https://t.me/nearnft

**Comment by ori-near** [comment]
@nearmax / @vlad-kopcil – I discussed this ticket from @ailisp, and he had a question about how we want to store the data. We have a few potential options:

1. Fetching the latest feed (e.g. last 1000 messages) from Telegram and not storing them in the smart contract.
2. Storing the Telegram messages in a smart contract by creating a post / other data type for each Telegram message.
3. Storing the Telegram messages in a database/backend

Bo recommends we proceed with option #1. Please let us know if you have any concerns or alternatives.

**Comment by nearmax** [comment]
In general, we should try avoiding any middleware or backend as much as possible, because DevDAO is not going to have large operations to be responsible for many services. I was thinking about two options:
* Store synced Telegram messages in SocialDB;
  * Pros:
    * It does not make the code of the main contact more complex.
    * The confirmation UX it simplified, because today when you call a method of a smart contract which is not SocialDB it always shows you a transaction confirmation window, while with SocialDB interactions it frequently skips it -- this will however become relevant only once we add a bi-directional sync.
    * Telegram messages are low-value, unlike standard posts on our board. Therefore we can experiment as much as we want with SocialDB without the fear of losing messages.
  * Cons:
    * Splits our business logic into two contracts. However, I think there is a good chance that at some point in the future we will be creating all posts in SocialDB and our contract will be just storing links to them, so this option is just aligned with the potential future design. 
    * Does not allow access control for who can create a message on the UI side (assuming we are going to have a bi-directional sync at some point). However, I am not sure this will ever be a problem, because Telegram channels are either completely permissionless (CG) or entirely read-only (WG).
* Store synced Telegram messages in the Gigs Board contracts. Pros and Cons are opposite to the above points.

In general, I am leaning with the first approach. However, I am also fine with Bo's first option if it is faster to implement, especially since it sounds like a pure UI feature.

I also think we should be storing all Telegram messages, but in the case of SocialDB option it does not even matter, because they way it works is that it permanently stores all key-value entires in storage-efficient manner.

Also, Illia suggested to look at https://near.social/#/wendersonpires.near/widget/ChatV2 for whether we can integrate with it or reuse some code, or just use it for UI inspiration.

**Comment by frol** [comment]
Just one piece of context, it is better to avoid storing all the messages in the contract storage. SocialDB posts are actually a single key `post` key updated with every newly published post, and all the previous posts are basically previous versions of the `post` value, which is why the link to a post on near.social is just `account_id` + `block_height`: https://near.social/#/mob.near/widget/MainPage.Post.Page?accountId=root.near&blockHeight=90195309. Indexer is required to maintain a list of messages. We may consider to keep a history of up to 1k messages in the contract storage for the time being, but it is not feasible nor useful to store all the chat messages in the contract storage.
